### ISSUE TITLE
[Shameless Plug] use react-preview at work

### ISSUE THREAD

**Issue by itaditya** [colshacol/jits#3]
Hi, thanks for building this, it looks really helpful.
I was reading your motivation for building this, and as you mentioned, the developers at your company use CodeSandbox to see if a PR breaks something.

The same thing motivated me to build [`react-preview`](https://github.com/apps/react-preview). It's a github app with which you can get a link to codesandbox just by commenting `/preview` on the PR.

For now, I have intentionally limited it to be used with react, however it works with all frontend libs and frameworks.

It would be great if I can get any feedback.

**Comment by colshacol** [comment]
For sure, my friend. I'll see if we can give it a shot here at Copart!
